# monicaちゃん調べ
version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db

    networks:
      - app-network

  db:
    image: mysql:8.0
    # restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: teamb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

  redis:
    image: redis
    # restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
